apiVersion: v1
kind: PersistentVolume
metadata:
  name: rmq-pv-learn
  namespace: rmq-learn
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: db-local-dev
  local:
    path: /mnt/message-brokers/rmq-learn
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - asp-node-01