apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rmq-learn-pvc
  namespace: rmq-learn
  labels:
    app: rabbitmq
    environment: learn
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: rmq-local-learn